"""Единый реестр issue_tags. Промпт и enum схемы читают этот список."""

ISSUE_TAGS = (
    "aim-calibration",
    "balance",
    "ball-feel",
    "biomechanics-first",
    "clear-intention",
    "contact-point",
    "effortless-power",
    "footwork",
    "form-vs-technique",
    "free-hitting",
    "gradual-acceleration",
    "grip",
    "ground-force",
    "hip-rotation",
    "mezhdudarnoe-vremya",
    "racket-as-weight",
    "racquet-path",
    "repeatable-swing",
    "shoulder-rotation",
    "split-step",
    "still-head",
    "strike-zone",
    "time-perception",
    "topspin-roll",
    "unit-turn",
    "universal-swing",
    "visual-illusions",
    "weight-transfer",
    "late-contact",
    "no-split-step",
    "toss-placement",
    "toss-height",
    "trophy-position",
    "knee-bend-drive",
    "contact-height",
    "arm-deceleration",
    "serve-finish-balance",
    "contact-in-front",
    "spacing-to-ball",
    "non-dominant-hand",
    "volley-backswing-too-long",
    "volley-contact-in-front",
    "ready-position-net",
    "recovery-position",
    "small-adjustment-steps",
    "first-step-direction",
)


def issue_tag_slugs() -> list:
    """Slug проблем, которые модели разрешено писать в issue_tags."""
    return list(ISSUE_TAGS)
